GLOBAL_LIST_INIT(city_ambience, list(
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_02.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_03.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_04.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_05.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_06.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_07.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_08.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_09.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_11.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_by_12.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_02.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_03.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_04.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_05.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_06.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_08.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/car_honk_09.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/plane_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/plane_02.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_02.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_03.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_04.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_05.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/yell_06.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_01.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_02.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_03.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_04.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_05.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_06.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_07.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_08.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_09.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_10.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_01.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_02.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_03.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_04.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_05.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_06.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_07.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_08.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_09.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_10.ogg',
))

GLOBAL_LIST_INIT(beach_ambience, list(
	'modular_darkpack/modules/ambience/sounds/nature/dog_01.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_02.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_03.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/dog_04.ogg',
))

GLOBAL_LIST_INIT(nature_ambience, list(
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_11.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_12.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_13.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_14.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_15.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_16.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/crow_caw_17.ogg',
))

GLOBAL_LIST_INIT(sewer_ambience, list(
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_01.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_02.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_03.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_04.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_05.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_06.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_07.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_08.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_09.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/pigeons_10.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_run.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_01.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_02.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_03.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_04.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_05.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_06.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_07.ogg',
	'modular_darkpack/modules/ambience/sounds/nature/rat_squeak_08.ogg',
))

GLOBAL_LIST_INIT(office_ambience, list(
	'modular_darkpack/modules/ambience/sounds/city_oneshots/wood_creak_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/wood_creak_02.ogg',
))

GLOBAL_LIST_INIT(tower_ambience, list(
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_01.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_02.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_03.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_04.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_05.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_06.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_07.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_08.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_09.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_10.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_11.ogg',
	'modular_darkpack/modules/ambience/sounds/city_oneshots/woodtower_creak_12.ogg',
))

GLOBAL_LIST_INIT(music_assoc,list(
	MUSIC_CITY = list('modular_darkpack/modules/ambience/sounds/music/downtown.ogg', 'modular_darkpack/modules/ambience/sounds/music/downtown_alt.ogg', 'modular_darkpack/modules/ambience/sounds/music/what_comes_next.ogg', 'modular_darkpack/modules/ambience/sounds/music/vtm_redemption_nyc_hub.ogg'),
	MUSIC_FOREST = list('modular_darkpack/modules/ambience/sounds/music/night_ambience.ogg', 'modular_darkpack/modules/ambience/sounds/music/for_my_clan.ogg'),
	MUSIC_CHURCH = list('modular_darkpack/modules/ambience/sounds/music/hahihaho.ogg'),
	MUSIC_PRINCE = list('modular_darkpack/modules/ambience/sounds/music/prince.ogg', 'modular_darkpack/modules/ambience/sounds/music/elysium.ogg'),
	MUSIC_BAR = list('modular_darkpack/modules/ambience/sounds/music/naive.ogg'),
	MUSIC_HOLLYWOOD = list('modular_darkpack/modules/ambience/sounds/music/hollywood.ogg', 'modular_darkpack/modules/ambience/sounds/music/open_season.ogg', 'modular_darkpack/modules/ambience/sounds/music/is_it_all_worth_it.ogg'),
	MUSIC_SANTAMONICA = list('modular_darkpack/modules/ambience/sounds/music/santamonica.ogg'),
	MUSIC_SAFE = list('modular_darkpack/modules/ambience/sounds/music/volition.ogg', 'modular_darkpack/modules/ambience/sounds/music/safe_room.ogg'),
	MUSIC_ENDRON = list ('modular_darkpack/modules/ambience/sounds/music/endron_for_the_planet.ogg'),
	MUSIC_CAERN = list ('modular_darkpack/modules/ambience/sounds/music/lux_umbrae.ogg')))
